### ISSUE TITLE
Can't install newest version of mosquito.

### ISSUE THREAD

**Issue by peoplenamed** [robacarp/mosquito#33]
I get an error after adding mosquito to my shards.yml. Using version 0.2.0 works but anything newer breaks redis.

_Error resolving redis (~> 2.0.0, *, ~> 2.1.1)_

Using amber (0.28.0 at master)
Using amber_router (0.3.0)
Using cli (0.7.0)
Using optarg (0.5.8)
Using callback (0.6.3)
Using string_inflection (0.2.1)
Using compiled_license (0.1.3)
Using kilt (0.4.0)
Using liquid (0.3.0)
Using inflector (0.1.8)
Using micrate (0.3.3)
Using db (0.5.1)
Using mysql (0.6.0)
Using pg (0.16.1)
Using redis (2.0.0)
Using pool (0.2.3)
Using shell-table (0.9.2 at 078a04ea58ead5203bb435a3b5fff448ddabaeea)
Using slang (1.7.1)
Using sqlite3 (0.11.0)
Using teeplate (0.7.0)
Using exception_page (0.1.2)
Using granite (0.15.2)
Using quartz_mailer (0.5.3)
Using email (0.3.3)
Using jasper_helpers (0.2.4)
Using citrine-i18n (0.3.2)
Using i18n (0.2.0)
Installing mosquito (0.2.0)
Using garnet_spec (0.2.1)
Using selenium (0.4.0)

**Comment by robacarp** [comment]
@peoplenamed this is a dup of #32, but I never was able to get to the bottom of it. Can you give me a little history, and post your shard.yml file too? I'm as yet unable to replicate this.

**Comment by D1ceWard** [comment]
I got the same problem... it seems that amber require an older version of redis (2.0.0) which create conflict with mosquito, since the new version of redis doesn't change much for amber, i just forked and changed redis version for myself (D1ceWard/amber), but i think we should ask on amber to unpin redis version (or any better solution) since they have like 999+ pull requests to update redis version (for non-breaking changes)

**Comment by robacarp** [comment]
@D1ceWard if you'll submit a pull request to Amber with your change, I'd be happy to review it :) Thanks for getting to the bottom of this.
