### ISSUE TITLE
Granite is required as dependency

### ISSUE THREAD

**Issue by greenbigfrog** [robacarp/mosquito#36]
You seam to be referencing `Granite` here, which causes a compilation issue if you don't have granite in your project anyway already. I don't think it's intended to be like this

https://github.com/robacarp/mosquito/blob/a1ade883a060b1ae7526fea4c6a09aea6b61a9f9/src/mosquito/base.cr#L2

**Comment by robacarp** [comment]
I know that it does work without Granite in the project, or at least it did recently.

Can you send the error you're getting? [this file](https://github.com/robacarp/mosquito/blob/master/src/external_classes.cr#L1) is included which declares a bare class to hold the place of Granite when it's not in the project. If that's stopped working, that may be due to a recent change in Crystal itself, or to a configuration issue.
